export type InvestmentKey = keyof typeof investmentData;
export const investmentData = {
  'QUIPUSWAP-PLENTY': {
    id: 'QUIPUSWAP-PLENTY',
    platform: 'quipuswap',
    address: 'KT1X1LgNkQShpF9nRLYw3Dgdy4qp38MX617z',
    decimals: 6,
    info: [],
    alias: 'QuipuSwap PLENTY',
    icons: ['QUIPUSWAP', 'PLENTY'],
    token: null,
    liquidityToken: true,
  },
  'QUIPUSWAP-KUSD': {
    id: 'QUIPUSWAP-KUSD',
    platform: 'quipuswap',
    address: 'KT1K4EwTpbvYN9agJdjpyJm4ZZdhpUNKB3F6',
    decimals: 6,
    info: [],
    alias: 'QuipuSwap kUSD',
    icons: ['QUIPUSWAP', 'kUSD'],
    token: null,
    liquidityToken: true,
  },
  'QUIPUSWAP-USDtz': {
    id: 'QUIPUSWAP-USDtz',
    platform: 'quipuswap',
    address: 'KT1WxgZ1ZSfMgmsSDDcUn8Xn577HwnQ7e1Lb',
    decimals: 0,
    info: [],
    alias: 'QuipuSwap USDtz',
    icons: ['QUIPUSWAP', 'USDTZ'],
    token: null,
    liquidityToken: true,
  },
  'QUIPUSWAP-ETHtz': {
    id: 'QUIPUSWAP-ETHtz',
    platform: 'quipuswap',
    address: 'KT1Evsp2yA19Whm24khvFPcwimK6UaAJu8Zo',
    decimals: 0,
    info: [],
    alias: 'QuipuSwap ETHtz',
    icons: ['QUIPUSWAP', 'ETHTZ'],
    token: null,
    liquidityToken: true,
  },
  'QUIPUSWAP-CRUNCH': {
    id: 'QUIPUSWAP-CRUNCH',
    platform: 'quipuswap',
    address: 'KT1RRgK6eXvCWCiEGWhRZCSVGzhDzwXEEjS4',
    decimals: 0,
    info: [],
    alias: 'QuipuSwap CRUNCH',
    icons: ['QUIPUSWAP', 'CRUNCH'],
    token: null,
    liquidityToken: true,
  },
  'PLENTY-XTZ-LP': {
    id: 'PLENTY-XTZ-LP',
    platform: 'plenty',
    address: 'KT1JQAZqShNMakSNXc2cgTzdAWZFemGcU6n1',
    decimals: 18,
    info: [],
    alias: 'PLENTY-XTZ LP farm',
    icons: ['PLENTY', 'XTZ'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-wBUSD': {
    id: 'PLENTY-wBUSD',
    platform: 'plenty',
    address: 'KT1KJhxkCpZNwAFQURDoJ79hGqQgSC9UaWpG',
    decimals: 18,
    info: [],
    alias: 'Plenty-wBUSD LP farm',
    icons: ['PLENTY', 'wBUSD'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-wUSDC': {
    id: 'PLENTY-wUSDC',
    platform: 'plenty',
    address: 'KT1Kp3KVT4nHFmSuL8bvETkgQzseUYP3LDBy',
    decimals: 12,
    info: [],
    alias: 'Plenty-wUSDC LP farm',
    icons: ['PLENTY', 'wUSDC'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-wWBTC': {
    id: 'PLENTY-wWBTC',
    platform: 'plenty',
    address: 'KT1M82a7arHVwcwaswnNUUuCnQ45xjjGKNd1',
    decimals: 13,
    info: [],
    alias: 'Plenty-wWBTC LP farm',
    icons: ['PLENTY', 'wWBTC'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-USDtz-LP': {
    id: 'PLENTY-USDtz-LP',
    platform: 'plenty',
    address: 'KT1VCrmywPNf8ZHH95HKHvYA4bBQJPa8g2sr',
    decimals: 12,
    info: [],
    alias: 'PLENTY-USDtz LP farm',
    icons: ['PLENTY', 'USDtz'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-wMATIC-LP': {
    id: 'PLENTY-wMATIC-LP',
    platform: 'plenty',
    address: 'KT1UP9XHQigWMqNXYp9YXaCS1hV9jJkCF4h4',
    decimals: 18,
    info: [],
    alias: 'PLENTY-wMATIC LP farm',
    icons: ['PLENTY', 'wMATIC'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-wLINK-LP': {
    id: 'PLENTY-wLINK-LP',
    platform: 'plenty',
    address: 'KT1UqnQ6b1EwQgYiKss4mDL7aktAHnkdctTQ',
    decimals: 18,
    info: [],
    alias: 'PLENTY-wLINK LP farm',
    icons: ['PLENTY', 'wLINK'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-hDAO-LP': {
    id: 'PLENTY-hDAO-LP',
    platform: 'plenty',
    address: 'KT1W3DtcPXbD7MMmtUdk3F352G6CYFSpwUUS',
    decimals: 12,
    info: [],
    alias: 'PLENTY-hDAO LP farm',
    icons: ['PLENTY', 'hDAO'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-ETHtz-LP': {
    id: 'PLENTY-ETHtz-LP',
    platform: 'plenty',
    address: 'KT1EVfYFoSpte3PnE4tPoWuj1DhNPVQwrW5Y',
    decimals: 18,
    info: [],
    alias: 'PLENTY-ETHtz LP farm',
    icons: ['PLENTY', 'ETHtz'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-wWETH-LP': {
    id: 'PLENTY-wWETH-LP',
    platform: 'plenty',
    address: 'KT1CBh8BKFV6xAH42hEdyhkijbwzYSKW2ZZC',
    decimals: 18,
    info: [],
    alias: 'PLENTY-wWETH LP farm',
    icons: ['PLENTY', 'wWETH'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-kUSD-LP': {
    id: 'PLENTY-kUSD-LP',
    platform: 'plenty',
    address: 'KT1MmAy4mSbZZVzPoYbK3M4z3GWUo54UTiQR',
    decimals: 18,
    info: [],
    alias: 'PLENTY-kUSD LP farm',
    icons: ['PLENTY', 'kUSD'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-QUIPU-LP': {
    id: 'PLENTY-QUIPU-LP',
    platform: 'plenty',
    address: 'KT1FsMiweyRTog9GGNC22hiMTFVRPrGs3eto',
    decimals: 12,
    info: [],
    alias: 'PLENTY-QUIPU LP farm',
    icons: ['PLENTY', 'QUIPU'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-tzBTC-LP': {
    id: 'PLENTY-tzBTC-LP',
    platform: 'plenty',
    address: 'KT1RwFV1xQU2E9TsXe1qzkdwAgFWaKk8bfAa',
    decimals: 13,
    info: [],
    alias: 'PLENTY-tzBTC LP farm',
    icons: ['PLENTY', 'tzBTC'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-WRAP-LP': {
    id: 'PLENTY-WRAP-LP',
    platform: 'plenty',
    address: 'KT1K9kLuhq9AJjDAgbJdKGBiP9927WsRnjP6',
    decimals: 13,
    info: [],
    alias: 'PLENTY-WRAP LP farm',
    icons: ['PLENTY', 'WRAP'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-UNO-LP': {
    id: 'PLENTY-UNO-LP',
    platform: 'plenty',
    address: 'KT1CWNVmHs6RRbLzwA3P19h7Wa9smnDrAgpS',
    decimals: 13,
    info: [],
    alias: 'PLENTY-UNO LP farm',
    icons: ['PLENTY', 'UNO'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-SMAK-LP': {
    id: 'PLENTY-SMAK-LP',
    platform: 'plenty',
    address: 'KT1VwZPZ4bcPQYS1C4yRvmU4giQDXhEV81WD',
    decimals: 10,
    info: [],
    alias: 'PLENTY-SMAK LP farm',
    icons: ['PLENTY', 'SMAK'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-KALAM-LP': {
    id: 'PLENTY-KALAM-LP',
    platform: 'plenty',
    address: 'KT1UTvMuyRggQe9q1hrh7YLh7vxffX2egtS6',
    decimals: 14,
    info: [],
    alias: 'PLENTY-KALAM LP farm',
    icons: ['PLENTY', 'KALAM'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-uUSD-LP': {
    id: 'PLENTY-uUSD-LP',
    platform: 'plenty',
    address: 'KT1HSYQ9NLTQufuvNUwMhLY7B9TX8LDUfgsr',
    decimals: 14,
    info: [],
    alias: 'Plenty-uUSD LP farm',
    icons: ['PLENTY', 'uUSD'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-wUSDT-LP': {
    id: 'PLENTY-wUSDT-LP',
    platform: 'plenty',
    address: 'KT1S4XjwGtk55TmsMqSdazEMrH4pGA3NMXhz',
    decimals: 12,
    info: [],
    alias: 'Plenty-wUSDT LP farm',
    icons: ['PLENTY', 'wUSDT'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-wDAI-LP': {
    id: 'PLENTY-wDAI-LP',
    platform: 'plenty',
    address: 'KT1FJzDx9AwbuNHjhzQuUxxKUMA9BQ7DVfGn',
    decimals: 18,
    info: [],
    alias: 'Plenty-wDAI LP farm',
    icons: ['PLENTY', 'wDAI'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-YOU-LP': {
    id: 'PLENTY-YOU-LP',
    platform: 'plenty',
    address: 'KT1MkXtVBuCKtxqSh7APrg2d7ThGBmEf4hnw',
    decimals: 15,
    info: [],
    alias: 'Plenty-YOU LP farm',
    icons: ['PLENTY', 'YOU'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'PLENTY-Ctez-LP': {
    id: 'PLENTY-Ctez-LP',
    platform: 'plenty',
    address: 'KT1MfMMsYX34Q9cEaPtk4qkQ6pojA7D2nsgr',
    decimals: 12,
    info: [],
    alias: 'Plenty-Ctez LP farm',
    icons: ['PLENTY', 'Ctez'],
    rewardToken: 'PLENTY',
    liquidityToken: true,
  },
  'uUSD-YOU-LP': {
    id: 'uUSD-YOU-LP',
    platform: 'plenty',
    address: 'KT1KGKzNGX1NDP3hGcipzyqVMCkwWbH76NJU',
    decimals: 12,
    info: [],
    alias: 'uUSD-YOU LP farm',
    icons: ['uUSD', 'YOU'],
    rewardToken: 'YOU',
    liquidityToken: true,
  },
  'uUSD-wUSDC-LP': {
    id: 'uUSD-wUSDC-LP',
    platform: 'plenty',
    address: 'KT1DfYVe4CaE9S6Sm3SEfhFYVZ9XzJbkQDqs',
    decimals: 9,
    info: [],
    alias: 'uUSD-wUSDC LP farm',
    icons: ['uUSD', 'wUSDC'],
    rewardToken: 'YOU',
    liquidityToken: true,
  },
  'uUSD-uDEFI-LP': {
    id: 'uUSD-uDEFI-LP',
    platform: 'plenty',
    address: 'KT1RENb4rWNFPP5QJSYT4rRGGsk1tPgLLwu2',
    decimals: 12,
    info: [],
    alias: 'uUSD-uDEFI LP farm',
    icons: ['uUSD', 'uDEFI'],
    rewardToken: 'YOU',
    liquidityToken: true,
  },
  'xPLENTY-Staking': {
    id: 'xPLENTY-Staking',
    platform: 'plenty',
    address: 'KT1Rpviewjg82JgjGfAKFneSupjAR1kUhbza',
    decimals: 18,
    info: [],
    alias: 'xPLENTY-Staking',
    icons: ['xPLENTY'],
    rewardToken: 'xPLENTY',
    liquidityToken: false,
  },
  'WRAP-STACKING': {
    id: 'WRAP-STACKING',
    platform: 'wrap',
    type: 'stacking',
    address: 'KT1EVn7eG9jZVpm8y9uRAwTocdwJzF6g2iKy',
    decimals: 8,
    info: [],
    alias: 'Wrap Stacking',
    icons: ['WRAP'],
    rewardToken: 'WRAP',
    liquidityToken: false,
  },
  'CRUNCHY-FARMS': {
    id: 'CRUNCHY-FARMS',
    platform: 'crunchy',
    address: 'KT1KnuE87q1EKjPozJ5sRAjQA24FPsP57CE3',
    decimals: 6,
    info: [],
    alias: 'Crunchy.Network Farms V1',
    icons: ['crDAO'],
    token: 'CRUNCH',
  },
  'PAUL-PAUL': {
    id: 'PAUL-PAUL',
    platform: 'paul',
    address: 'KT1DMCGGiHT2dgjjXHG7qh1C1maFchrLNphx',
    decimals: 8,
    info: [],
    alias: 'PAUL farm',
    icons: ['PAUL'],
    rewardToken: 'PAUL',
    liquidityToken: false,
  },
  'PAUL-XTZ': {
    id: 'PAUL-XTZ',
    platform: 'paul',
    address: 'KT1WfbRVLuJUEizo6FSTFq5tsi3rsUHLY7vg',
    decimals: 6,
    info: ['quipuswap-lqt'],
    alias: 'PAUL/XTZ farm',
    icons: ['PAUL', 'XTZ'],
    rewardToken: 'PAUL',
    liquidityToken: true,
  },
  'MAG-XTZ': {
    id: 'MAG-XTZ',
    platform: 'paul',
    address: 'KT1JTbVbs4iCjYiBqeNBHqHkAztaTvB6qgJK',
    decimals: 6,
    info: ['quipuswap-lqt'],
    alias: 'MAG/XTZ farm',
    icons: ['MAG', 'XTZ'],
    rewardToken: 'PAUL',
    liquidityToken: true,
  },
  'QUIPU-PAUL': {
    id: 'QUIPU-PAUL',
    platform: 'paul',
    address: 'KT1M3a9PaWfBNTYibToVqZ3DChuk1x9Torwr',
    decimals: 6,
    info: ['paul-lqt'],
    alias: 'QUIPU/PAUL farm',
    icons: ['QUIPU', 'PAUL'],
    rewardToken: 'PAUL',
    liquidityToken: true,
  },
  'crDAO-XTZ': {
    id: 'crDAO-XTZ',
    platform: 'paul',
    address: 'KT1BcSP2rE7bHpouNzWBb3MfNVZFcdaRWPta',
    decimals: 6,
    info: ['paul-lqt'],
    alias: 'crDAO/QUIPU farm',
    icons: ['crDAO', 'QUIPU'],
    rewardToken: 'PAUL',
    liquidityToken: true,
  },
  'QUIPU-XTZ': {
    id: 'QUIPU-XTZ',
    platform: 'paul',
    address: 'KT1EiG7Xo1JTd3Q4kGnmM6eYqXW1EaYk4wZW',
    decimals: 6,
    info: ['paul-lqt'],
    alias: 'QUIPU/XTZ farm',
    icons: ['QUIPU', 'XTZ'],
    rewardToken: 'PAUL',
    liquidityToken: true,
  },
  'PAUL-crDAO': {
    id: 'PAUL-crDAO',
    platform: 'paul',
    address: 'KT1Uoj71GA7oBbXHqnZTZmHQRCDuyaDs4zDR',
    decimals: 6,
    info: ['paul-lqt'],
    alias: 'PAUL/crDAO farm',
    icons: ['PAUL', 'crDAO'],
    rewardToken: 'PAUL',
    liquidityToken: true,
  },
  'QUIPU-crDAO': {
    id: 'QUIPU-crDAO',
    platform: 'paul',
    address: 'KT1H8k3hKQ1FyhbXkxg13ihTJXHB6uEWvzmP',
    decimals: 6,
    info: ['paul-lqt'],
    alias: 'QUIPU/crDAO farm',
    icons: ['QUIPU', 'crDAO'],
    rewardToken: 'PAUL',
    liquidityToken: true,
  },
  'wWBTC-PAUL': {
    id: 'wWBTC-PAUL',
    platform: 'paul',
    address: 'KT1UDwFmuyAbCCC6YSJvNVQPwNGjW91W2HDf',
    decimals: 6,
    info: ['paul-lqt'],
    alias: 'wWBTC/PAUL farm',
    icons: ['wWBTC', 'PAUL'],
    rewardToken: 'PAUL',
    liquidityToken: true,
  },
  'wUSDC-PAUL': {
    id: 'wUSDC-PAUL',
    platform: 'paul',
    address: 'KT1Lm2C7TsRi4EMQj2sxpr3iD1jpck1MXXSY',
    decimals: 6,
    info: ['paul-lqt'],
    alias: 'wUSDC/PAUL farm',
    icons: ['wUSDC', 'PAUL'],
    rewardToken: 'PAUL',
    liquidityToken: true,
  },
  'wWETH-PAUL': {
    id: 'wWETH-PAUL',
    platform: 'paul',
    address: 'KT1UcYH3CLtKL393rHEEkFphWjZNzeHtLEXB',
    decimals: 6,
    info: ['paul-lqt'],
    alias: 'wWETH/PAUL farm',
    icons: ['wWETH', 'PAUL'],
    rewardToken: 'PAUL',
    liquidityToken: true,
  },
  'PAUL-uUSD': {
    id: 'PAUL-uUSD',
    platform: 'paul',
    address: 'KT1D5VoidRrC4G2HDXpSUfAVaccGpzWJsE3r',
    decimals: 6,
    info: ['paul-lqt'],
    alias: 'PAUL/uUSD farm',
    icons: ['PAUL', 'uUSD'],
    rewardToken: 'PAUL',
    liquidityToken: true,
  },
  'PAUL-kUSD-uUSD': {
    id: 'PAUL-kUSD-uUSD',
    platform: 'paul',
    address: 'KT1UonD6xnLqQcK3pSBXreXVYUGzUkF8DmHS',
    decimals: 6,
    info: ['paul-lqt'],
    alias: 'kUSD/uUSD farm',
    icons: ['kUSD', 'uUSD'],
    rewardToken: 'PAUL',
    liquidityToken: true,
  },
  'KUSD-QUIPU-LP': {
    id: 'KUSD-QUIPU-LP',
    platform: 'kdao',
    address: 'KT1RB179ddATKbCi7E8ben91bo2hqRRPrNQf',
    decimals: 6,
    info: [],
    alias: 'kUSD Quipu LP Farm',
    icons: ['kUSD', 'QUIPUSWAP'],
    rewardToken: 'kDAO',
    liquidityToken: true,
  },
  'KUSD-KDAO': {
    id: 'KUSD-KDAO',
    platform: 'kdao',
    address: 'KT1HDXjPtjv7Y7XtJxrNc5rNjnegTi2ZzNfv',
    decimals: 18,
    info: [],
    alias: 'kUSD Farm',
    icons: ['kUSD', 'kDAO'],
    rewardToken: 'kDAO',
    liquidityToken: false,
  },
  'KUSD-QL': {
    id: 'KUSD-QL',
    platform: 'kdao',
    address: 'KT18oxtA5uyhyYXyAVhTa7agJmxHCTjHpiF7',
    decimals: 36,
    info: [],
    alias: 'QL kUSD Farm',
    icons: ['QUIPUSWAP'],
    rewardToken: 'kDAO',
    liquidityToken: true,
  },
};
